apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit323-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sit323-app
  template:
    metadata:
      labels:
        app: sit323-app
    spec:
      containers:
      - name: sit323-app
        image: jirongling/sit323-app:latest
        ports:
        - containerPort: 8080
